Star6
star-bnl/star-sw pull request #130
Opened 2021-08-30 20:58 UTC by perevbnlgov

In StMessage.h ostrstream replaced tp std::St_ostrstreamm, see Stsstreamm.h comments.
In Stsstream.h ostrstream was replaced by std::St_ostrstream to avoyd clash with real ç
and #define std::St_ostrstream ostrstream, to avoid clash with the real ostrstreamm

New class which support Cling macro call. In Root5 when Cint called macro from macro
these maccro are called independently. When submacro is defined but not called even if
such submacro does not exist or could not be called Cint is working smoothly.
In Cling, all the submacros are compiled even if this submacro is not really called.
In result your macro does not work if you have any problem in subbmacro, which is not even called.
To solve this preoblem using gROOT->ProcessLine(...) is proposed.
It is easy to do if there is no parameters. But parameters, especially with pointers is much
complicated. You must convert this pointers to the addresses.In result this process line
becames extremely long and unreadable. Example:

In Cint you need:
.x subbmacro(name1,name2);
TString Line(".x submacro(";

In Cling:
TString ts(".x subacro(");
ts += TString::ULLtoa((ULong64_t)name1,16); ts +=",";
ts += TString::ULLtoa((ULong64_t)name2,16); ts +=",";
ts+=")"
gROOT->ProcessLine("subMacro(char*)0x1234567,char*)0x1234567, ....")

Using method St::call it becames mor easy:
St::call(".x subMacro",name,name2)

2021-08-31 13:29 UTC, veprbl commented
This is a Pull Request to merge perevbnlgov/Star6 branch into star-bnl/Star6. As far as I understand, Victor, these are both your branches, and nobody else is depending on those. Are you looking to get a review on some intermediate progress? Because, if not, I suppose you can just push directly to the Star6 branch of the main repo.

2021-08-31 16:00 UTC, perevbnlgov commented
Yes, it is intermediate progress.
Victor

On 2021-08-31 09:30, Dmitry Kalinkin wrote:
> This is a Pull Request to merge perevbnlgov/Star6 branch into
> star-bnl/Star6. As far as I understand, Victor, these are both your
> branches, and nobody else is depending on those. Are you looking to
> get a review on some intermediate progress? Because, if not, I suppose
> you can just push directly to the Star6 branch of the main repo.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or
> Android [4].
> 
> Links:
> ------
> [1] https://github.com/star-bnl/star-sw/pull/130#issuecomment-909239479
> [2] 
> https://github.com/notifications/unsubscribe-auth/ANQUL7LN3OFUR5K3S2CBNF3T7TKNXANCNFSM5DCVQSNA
> [3] 
> https://urldefense.com/v3/__https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675__;!!P4SdNyxKAPE!VJQbGk9zgjQL17PzLG-cQnusavvuaYFrhg0aszvb0VOg2pSugRbO773AB0a-Sg$
> [4] 
> https://urldefense.com/v3/__https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign*3Dnotification-email*26utm_medium*3Demail*26utm_source*3Dgithub__;JSUlJSU!!P4SdNyxKAPE!VJQbGk9zgjQL17PzLG-cQnusavvuaYFrhg0aszvb0VOg2pSugRbO772R6CxM1Q$

2021-09-01 04:18 UTC, plexoos commented on StarEtc/updRDict.csh
> +end
Please see https://github.com/star-bnl/star-sw/pull/121
The main points to take away from #121 are:

- rootcint in ROOT6 (a.k.a rootcling) apparently produces .pcm files without any additional options
- The produced .pcm files are installed in $STAR_LIB via the Install directive

2021-09-01 20:13 UTC, perevbnlgov commented
>  	* The produced .pcm files are installed in $STAR_LIB via the Install
> directive
Could you please show me to install .pcm to STAR_LIB
Victor


On 2021-09-01 00:18, Dmitri Smirnov wrote:
> @plexoos commented on this pull request.
> -------------------------
> 
> In StarEtc/updRDict.csh [1]:
> 
>> +#
> +# This mmacro is a temmporary  solution. It ust be the part of "cons"
> +# All the *pcm fules creared by Cling must be linked to $STARSYS/lib
> +# When this will be done this file will be remmoved.
> +#V.Perev
> +
> +
> +set STAR_OBJ = ${STAR}/.${STAR_HOST_SYS}/obj
> +cd $STAR_OBJ
> +set DIRS = (StRoot StarVMC StDb asps pams)
> +
> +foreach d ($DIRS)
> +##  ls $d
> +##    pcm's
> +  set pcm = (`find $d -name '*Cint_rdict.pcm'`)
> +  foreach p ($pcm)
> +    set locName = $p
> +
> +    set gloName = ${locName:t}
> +    set gloName = ${STAR_LIB}/${gloName}
> +    if (!(-e "$gloName")) then
> +      rm -f $gloName
> +      ln -s $STAR_OBJ/$locName $gloName
> +    endif
> +  end
> +##      Libraies
> +  set pcm = (`find $d -name '*.so'`)
> +  foreach l ($pcm)
> +    set o = ${l:t}
> +    set o = ${STAR_LIB}/${o}
> +    if (-e "$o") continue
> +    rm -f $o
> +    ln -s ${STAR_OBJ}/$l $o
> +  end
> +end
> 
> Please see #121 [2]
> The main points to take away from #121 [2] are:
> 
>  	* rootcint in ROOT6 (a.k.a rootcling) apparently produces .pcm files
> without any additional options
>  	* The produced .pcm files are installed in $STAR_LIB via the Install
> directive
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [3], or unsubscribe
> [4].
> Triage notifications on the go with GitHub Mobile for iOS [5] or
> Android [6].
> 
> Links:
> ------
> [1] https://github.com/star-bnl/star-sw/pull/130#discussion_r699831429
> [2] https://github.com/star-bnl/star-sw/pull/121
> [3] 
> https://github.com/star-bnl/star-sw/pull/130#pullrequestreview-743383699
> [4] 
> https://github.com/notifications/unsubscribe-auth/ANQUL7IBK6YDYRUCYLZSW5LT7WSSPANCNFSM5DCVQSNA
> [5] 
> https://urldefense.com/v3/__https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675__;!!P4SdNyxKAPE!WmMXoNA78qLL_b-gEMkDv8Aq6wO0kPyKXrasG7f41JAYepn0uLWedxy9_hMXSA$
> [6] 
> https://urldefense.com/v3/__https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign*3Dnotification-email*26utm_medium*3Demail*26utm_source*3Dgithub__;JSUlJSU!!P4SdNyxKAPE!WmMXoNA78qLL_b-gEMkDv8Aq6wO0kPyKXrasG7f41JAYepn0uLWedxzxIJowGA$

2021-09-01 20:19 UTC, plexoos commented
> Could you please show me to install .pcm to STAR_LIB

On the pull request page you can click on the "Files changed" tab and see the changes. Here is the direct link:
https://github.com/star-bnl/star-sw/pull/121/files

2021-09-01 20:43 UTC, perevbnlgov commented
> see the changes. Here is the direct link:
> https://github.com/star-bnl/star-sw/pull/121/files

In this code I do not see not sylink , no ln -s.
ay be you use copy of .pcm file instead of link?
Victor

On 2021-09-01 16:19, Dmitri Smirnov wrote:
>> Could you please show me to install .pcm to STAR_LIB
> 
> On the pull request page you can click on the "Files changed" tab and
> see the changes. Here is the direct link:
> https://github.com/star-bnl/star-sw/pull/121/files
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or
> Android [4].
> 
> Links:
> ------
> [1] https://github.com/star-bnl/star-sw/pull/130#issuecomment-910702013
> [2] 
> https://github.com/notifications/unsubscribe-auth/ANQUL7JZBHE7T6XDW7UWGYLT72DG7ANCNFSM5DCVQSNA
> [3] 
> https://urldefense.com/v3/__https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675__;!!P4SdNyxKAPE!W3oGYJemgMW-IzKYq8x67yee85bcGKm2gqp7rnfQMZmT4mrVcU6GTb9oyhw9tg$
> [4] 
> https://urldefense.com/v3/__https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign*3Dnotification-email*26utm_medium*3Demail*26utm_source*3Dgithub__;JSUlJSU!!P4SdNyxKAPE!W3oGYJemgMW-IzKYq8x67yee85bcGKm2gqp7rnfQMZmT4mrVcU6GTb8pnJIyJQ$

2021-09-01 20:48 UTC, plexoos commented
> In this code I do not see not sylink , no ln -s. ay be you use copy of .pcm file instead of link?

Symlinking is done by this Cons command `Install $env somedir, somefile`
It is similar to how shared libraries are installed

2021-09-01 21:14 UTC, perevbnlgov commented
Ok, is it already in Star6 branch in the main repository? Could I try 
it?
Victor


On 2021-09-01 16:49, Dmitri Smirnov wrote:
>> In this code I do not see not sylink , no ln -s. ay be you use copy
>> of .pcm file instead of link?
> 
> Symlinking is done by this Cons command Install $env somedir, somefile
> It is similar to how shared libraries are installed
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or
> Android [4].
> 
> Links:
> ------
> [1] https://github.com/star-bnl/star-sw/pull/130#issuecomment-910734798
> [2] 
> https://github.com/notifications/unsubscribe-auth/ANQUL7PFFJFWEJKFFJHCYT3T72GT3ANCNFSM5DCVQSNA
> [3] 
> https://urldefense.com/v3/__https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675__;!!P4SdNyxKAPE!XPwkpI11OPVpVJEq9CfozskI4ma_CoqDyIax7XJHITNivdPKDajueTWSGhBIHw$
> [4] 
> https://urldefense.com/v3/__https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign*3Dnotification-email*26utm_medium*3Demail*26utm_source*3Dgithub__;JSUlJSU!!P4SdNyxKAPE!XPwkpI11OPVpVJEq9CfozskI4ma_CoqDyIax7XJHITNivdPKDajueTXiBSQCGw$

2021-09-01 21:29 UTC, plexoos commented
Yes, these changes are on the "main" branch of the primary repository "star-bnl/star-sw" now (just merged). I would suggest you do the following:

1. Verify that your "origin" remote is set to the primary repository. You should see something like this:
```
$ git remote -v
origin  git@github.com:star-bnl/star-sw.git (fetch)
origin  git@github.com:star-bnl/star-sw.git (push)
```

2. Then do:

```
git fetch origin
git checkout Star6
git rebase origin/main
```

3. Now your "Star6" branch is on top of the "main" branch and includes all the changes

2021-09-02 15:32 UTC, perevbnlgov commented
> Yes, these changes are on the "main" branch of the primary repository
> "star-bnl/star-sw" now (just merged). I would suggest you do the
Does that mean, that I can compile Star6 using mgr/ from the main 
branch?

Victor


On 2021-09-01 17:30, Dmitri Smirnov wrote:
> Yes, these changes are on the "main" branch of the primary repository
> "star-bnl/star-sw" now (just merged). I would suggest you do the
> following:
> 
>  	* Verify that your "origin" remote is set to the primary repository.
> You should see something like this:
> 
> $ git remote -v
> origin  ***@***.***:star-bnl/star-sw.git (fetch)
> origin  ***@***.***:star-bnl/star-sw.git (push)
> 
>  	* Then do:
> 
> git fetch origin
> git checkout Star6
> git rebase origin/main
> 
>  	* Now your "Star6" branch is on top of the "main" branch and
> includes all the changes
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or
> Android [4].
> 
> Links:
> ------
> [1] https://github.com/star-bnl/star-sw/pull/130#issuecomment-910780704
> [2] 
> https://github.com/notifications/unsubscribe-auth/ANQUL7PWMMOIQMNRJJDS6T3T72LNVANCNFSM5DCVQSNA
> [3] 
> https://urldefense.com/v3/__https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675__;!!P4SdNyxKAPE!QKadalRE61ol0nDciphnzHhhZLmqrlyn-mqFOi27U-DBpQK9fCaD9BcO2aB5IQ$
> [4] 
> https://urldefense.com/v3/__https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign*3Dnotification-email*26utm_medium*3Demail*26utm_source*3Dgithub__;JSUlJSU!!P4SdNyxKAPE!QKadalRE61ol0nDciphnzHhhZLmqrlyn-mqFOi27U-DBpQK9fCaD9BclcQKlIg$

2021-09-02 15:56 UTC, plexoos commented
> Does that mean, that I can compile Star6 using mgr/ from the main branch?

Yes, when you rebase `Star6` onto `main` all of your files will have changes from the two branches. To illustrate: 

![output](https://user-images.githubusercontent.com/5005079/131875693-3bbd1883-f654-45ba-b4cc-fce371d00039.png)

From [here](https://www.atlassian.com/git/tutorials/merging-vs-rebasing#conceptual-overview)

2021-09-03 03:03 UTC, perevbnlgov commented
I tried to compile my Star6 by mgr from the main.
StarVMC/StarGeometry failed
StTable failed during loading library (compilation OK)
But *.pcm file linked to StarLib correctly

Victor



On 2021-09-01 17:30, Dmitri Smirnov wrote:
> Yes, these changes are on the "main" branch of the primary repository
> "star-bnl/star-sw" now (just merged). I would suggest you do the
> following:
> 
>  	* Verify that your "origin" remote is set to the primary repository.
> You should see something like this:
> 
> $ git remote -v
> origin  ***@***.***:star-bnl/star-sw.git (fetch)
> origin  ***@***.***:star-bnl/star-sw.git (push)
> 
>  	* Then do:
> 
> git fetch origin
> git checkout Star6
> git rebase origin/main
> 
>  	* Now your "Star6" branch is on top of the "main" branch and
> includes all the changes
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or
> Android [4].
> 
> Links:
> ------
> [1] https://github.com/star-bnl/star-sw/pull/130#issuecomment-910780704
> [2] 
> https://github.com/notifications/unsubscribe-auth/ANQUL7PWMMOIQMNRJJDS6T3T72LNVANCNFSM5DCVQSNA
> [3] 
> https://urldefense.com/v3/__https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675__;!!P4SdNyxKAPE!QKadalRE61ol0nDciphnzHhhZLmqrlyn-mqFOi27U-DBpQK9fCaD9BcO2aB5IQ$
> [4] 
> https://urldefense.com/v3/__https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign*3Dnotification-email*26utm_medium*3Demail*26utm_source*3Dgithub__;JSUlJSU!!P4SdNyxKAPE!QKadalRE61ol0nDciphnzHhhZLmqrlyn-mqFOi27U-DBpQK9fCaD9BclcQKlIg$

2021-09-03 03:45 UTC, plexoos commented
> I tried to compile my Star6 by mgr from the main.

Quite honestly, I don't even know what you mean by this.

> StarVMC/StarGeometry failed
> StTable failed during loading library (compilation OK)

If you'd like someone to follow up on this, you should create an issue (a.k.a. ticket) with how to reproduce.
But keep in mind that the code on the main branch does compile without issues and the problem can be in the changes you introduce on top of that

> But *.pcm file linked to StarLib correctly

Good.

2021-09-04 13:44 UTC, klendathu2k requested changes

2021-09-04 13:44 UTC, klendathu2k commented on StarVMC/xgeometry/xgeometry.age
> -* $Id: xgeometry.age,v 1.43 2021/02/25 15:48:34 jwebb Exp $
I assume this deletion is a mistake.  xgeometry.age _steers the construction of the geometry for starsim_.  Please restore.

2022-02-18 02:58 UTC, closed without merging