Add new FCS MC filters
star-bnl/star-sw pull request #17
Opened 2021-06-04 17:36 UTC by plexoos

This PR includes only new files and replaces #14 by @akioogawa 

> Those are code I used to maintain. I'm guessing I should request ownership. But I don't know what the new rules are....
> 
> Ummm sigh. Changes in
> StRoot/StFcsFastSimulatorMaker/macro/README.MC
> StarGenerator/FILT/Fcs*
> are in the other pull request #11 :(

2021-06-04 17:47 UTC, plexoos commented
Hi @akioogawa 
This changes are pending reviews by @klendathu2k and @perevbnlgov 

Do I understand correctly that these new files are not used in production for either real data or simulation?

2021-06-04 18:04 UTC, klendathu2k requested changes

2021-06-04 18:04 UTC, klendathu2k commented on StRoot/StarGenerator/FILT/FcsDYBGFilter.cxx
> +		if(pid1!=111 && pid1!=22 && abs(pid1)!=11) swap[idx1]=1;
At minimum, assert(idx1<1000 && idx2<1000).

Probably better to use std::map<int,int> swap instead of a fixed array.

2021-06-04 21:32 UTC, perevbnlgov approved these changes
I am not author of this code. I looked it and I did not find anything evidently wrong. Programming style somehow is different what I prefere. But it is not too important.
I have no objections to commit this code

2021-06-16 19:17 UTC, plexoos commented
@akioogawa Akio, if you want these files in the new release you should act now on the Jason's suggestions

2021-06-22 21:47 UTC, akioogawa commented
I did change array to std::vector. Pushed. I don't think I know what I'm doing with the my HEAD:PR20210603 branch

2021-06-22 22:03 UTC, plexoos commented
```
git remote add upstream git@github.com:star-bnl/star-sw.git
git fetch upstream
git checkout ds-fcs-mc-filter
# hack hack hack
git add
git commit
git push
```

2021-06-22 23:04 UTC, akioogawa commented
I've already did "git commit" and "git push origin HEAD:PR20210603".  I thought this pull request was on the PR20210603 branch I created on my GitHub. It seemed push was successful. But GitHub web page does not have the change :P. 

Following your suggestion blindly, "git fetch upstream" gives
  Permission denied (publickey).
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights and the repository exists.

And ugh, I guess commit is also not directly based but on the local copy, so that I committed something else as well to my local repo. I guess I need multiple local repo, and multiple github repo as well?

2021-06-23 20:20 UTC, akioogawa commented
I did setup ssh keys. 

I did successfully commit and push the change to my repo:
  https://github.com/akioogawa/star-sw/blob/main/StRoot/StarGenerator/FILT/FcsDYBGFilter.cxx
but this PR is on "ds-fcs-mc-filter" branch (I guess you created?).

If I do what you suggested at empty dir: 
  $ git remote add upstream git@github.com:star-bnl/star-sw.git
  fatal: not a git repository (or any parent up to mount point /direct)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

If I do it at dir (rcas6006.rcf.bnl.gov:/star/u/akio/git/star-s) where I checked out from my GitHub repo (https://github.com/akioogawa/star-sw.git)
   $ git remote add upstream git@github.com:star-bnl/star-sw.gita
   fatal: remote upstream already exists.

From empty dir, I did
  $ git remote add upstream git@github.com:star-bnl/star-sw.git
  $ git clone --no-checkout git@github.com:star-bnl/star-sw.git
  $ cd star-sw/
  $ git fetch upstream
  $ git checkout ds-fcs-mc-filter
which gives
  error: pathspec 'ds-fcs-mc-filter' did not match any file(s) known to git

Giving up for today.

2021-06-24 01:52 UTC, veprbl commented
> $ git remote add upstream git@github.com:star-bnl/star-sw.git
> $ git fetch upstream

So far so good.

> $ git checkout ds-fcs-mc-filter

The plain `git checkout <branchname>` switches your current branch to the branch `<branchname>`. At this point you can run `git branch` to see the list of the branches that your local repository has, and you probably will see only the `main` branch. What `git fetch upstream` does for you is it fetches commits referenced by branches existing on the remote repository, but unlike `git pull` it does not modify any of your local branches. The references to remote branches are copied as well, you can see them in the output of `git branch --all`. The reference you are looking for will be named `upstream/ds-fcs-mc-filter`, you can create a local `ds-fcs-mc-filter` pointing to that reference by doing `git checkout upstream/ds-fcs-mc-filter` followed by `git branch ds-fcs-mc-filter`. There is a shortcut for this operation: `git checkout -t upstream/ds-fcs-mc-filter`. You should then be able to add more commits and push your local branch back to the remote repository that you've called "upstream" using `git push upstream ds-fcs-mc-filter`.

2021-06-24 02:24 UTC, akioogawa commented
Thanks Veprbl. I was just following Plexoos's recipe. I read your comment 3 times. Yet I don't think I understood :( I guess I don't know what "references" is and how it is different from branches.

2021-06-24 02:38 UTC, veprbl commented
The original instruction posted above is incorrect. The combination of `git fetch upstream` + `git checkout ds-fcs-mc-filter` can not work. The second command would have to be `git checkout -t upstream/ds-fcs-mc-filters` (note there is also a missing `s`). I do appreciate how this may be confusing.

The idea behind references is that they are similar to branches, but unlike branches you are not supposed to change them yourself. Instead they are updated by service commands like `git fetch` and used to track what git believes to be the state of the remote repositories.

2021-06-24 16:29 UTC, akioogawa approved these changes

2021-06-24 16:36 UTC, veprbl commented on StRoot/StarGenerator/FILT/FcsDYBGFilter.cxx
> +    std::vector<int> swap(100);
This allocates a vector with 100 zero values that don't seem to be used in any way.
```suggestion
    std::vector<int> swap;
```

2021-06-24 18:35 UTC, veprbl approved these changes
Code looks a bit messy, but the logics seems right.

2021-06-25 13:56 UTC, klendathu2k approved these changes
Code looks good and can be merged.  No changes required, but a few recommendations made.  In particular, filters should only return a kAccept or kReject result.  There is one place where an error code is emitted, but that case should not happen.

2021-06-25 13:56 UTC, klendathu2k commented on StRoot/StarGenerator/FILT/FcsDYBGFilter.cxx
> +    if(np <= 0) {return kError;}
The filter method should only return an accept / reject decision.   If this line is commented out, the code will return a reject in the case where no particles were generated.  Recommend commenting this out.

2021-06-25 13:56 UTC, klendathu2k commented on StRoot/StarGenerator/FILT/FcsDYBGFilterSingle.cxx
> +static const float ZFCS    = 710.16 + 13.9 + 15.0;
Not critical, but you should consider making these parameters tunable (i.e. non-const, loadable from a configuration file...)

2021-06-25 14:48 UTC, merged