consolidating chain options for pppAMode
star-bnl/star-sw pull request #23
Opened 2021-06-09 16:05 UTC by BassamAboona

I made some edits to reduce the number of chain options required to turn on pppAMode. I also added a log message to indicate that pppAMode is on. For some reason, the spacing in StVpdCalibMaker.cxx looks funny. This is not the case with the local copy that I committed and pushed.

2021-06-09 16:27 UTC, fgeurts approved these changes, later dismissed

2021-06-09 19:39 UTC, fgeurts requested changes
I noticed that your PL includes adding two "swp" files. Please remove those. The proposed changes to the cxx files are fine.

2021-06-09 20:07 UTC, BassamAboona commented
> I noticed that your PL includes adding two "swp" files. Please remove those. The proposed changes to the cxx files are fine.

Sorry about that! They should both be deleted now.

2021-06-09 22:57 UTC, fgeurts approved these changes

2021-06-10 00:42 UTC, plexoos approved these changes

2021-06-10 04:58 UTC, merged