Star6 01
star-bnl/star-sw pull request #318
Opened 2022-03-06 20:53 UTC by perevbnlgov

Outdated StKF* and KFP* and KFV* removed. Code which is used it also removed.
According LinDef is changed. By request of Y.Fisyak

2022-03-07 14:56 UTC, ullrich-bnl approved these changes

2022-03-07 16:44 UTC, starsdong commented
Victor, thank you very much for pushing this forward. One quick question, the changes proposed in StBFChain in this PR don't seem to be related to the need for ROOT6. Or did I miss something here?
On the proposed changes to mgr/, Dmitri or Grigory would be nice to hear your comments. Thanks

2022-03-07 17:28 UTC, klendathu2k requested changes
Thank you for pruning this down to a minimal set of changes.  There are several issues identified, and a couple of questions.  

But I note that the CI builds have failed for both ROOT5 and ROOT6.  Regardless of getting two approvals, the code must actually compile under both ROOT5 and ROOT6... (under both cons and the CI builds).

2022-03-07 17:28 UTC, klendathu2k commented on StRoot/StBFChain/doc/BFC.h
> +Bfc_st BFC[] = {
Files under StBFChain/doc are generated during the build process.  They should not be committed into this directory.  (Use "git rm" to remove the files).

2022-03-07 17:28 UTC, klendathu2k commented on StRoot/StBFChain/doc/BFC2.h
> +Bfc_st BFC[] = {
Remove

2022-03-07 17:28 UTC, klendathu2k commented on StRoot/StBFChain/doc/StBFChain.cxx_doc
> +// @(#)StRoot/StBFChain:$Name:  $:$Id: StBFChain.cxx,v 1.670 2021/03/21 03:32:28 genevb Exp $
... looks like we are replacing a newer revision with an older one (1.670 vs 1.180)... but again, these files are generated at compile time.  Should remove this.

2022-03-07 17:28 UTC, klendathu2k commented on mgr/ConsDefs.pm
> +$CXXFLAGS .= "-fdiagnostics-color=always -msse4.2 -std=c++11 -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -DNDEBUG";
Not clear why we need the -msse4.2 option.  Is this for root 6, or are we just picking up a change for the heck of it?

Also... defines NDEBUG... which I am not convinced is the right thing to do here.  (Doesn't this break logic for creating debug vs nodebug builds?  Has this change to the CXXFLAGS been tested... beyond "it compiles, it runs, and plots can be made that sorta kinda look right")

2022-03-07 17:28 UTC, klendathu2k commented on mgr/RootCint.pl
> +    	$cmd  = "rootcling -rmf $Cint_map -f $Cint_cxx  -DROOT_CINT -D__ROOT__ $CPPFLAGS $h_files";
Does this work for our ROOT5 builds as well?  (This commit _cannot_ break the ROOT5 build.)

2022-03-07 17:28 UTC, klendathu2k commented on mgr/RootCint.pl
> +##    	die;
Yes.  Let's _really_ make sure this line is commented out ;)

2022-03-07 17:28 UTC, klendathu2k commented on mgr/RootCint.pl
> +    	$cmd  = "rootcling -rmf $Cint_map -f $Cint_cxx  -DROOT_CINT -D__ROOT__ $CPPFLAGS $h_files";
... probably should have logic testing against the root version we compile against, and use root5/rootcint versus root6/rootcling.

2022-03-07 17:28 UTC, klendathu2k commented on StRoot/StBFChain/StBFChain.cxx
> +printf ("UUU Mk = %p\n",mk);
This introduces a change to the StStrangeMuDstMaker configuration... and also creates meaningless output.

The old version needs to be restored.

2022-03-08 14:45 UTC, plexoos commented
> On the proposed changes to mgr/, Dmitri or Grigory would be nice to hear your comments. Thanks

I agree with the Jason's remarks. Before we continue with any further discussion the code should compile.

2022-03-09 04:09 UTC, perevbnlgov commented on StRoot/StBFChain/doc/BFC.h
> +Bfc_st BFC[] = {
Yes, I know, I am trying not to touch these doc files, ut they are arised again. I did not find how to ignore them.
Best of all to remove them at all. Automatically created files should not be in ane CVS or Git repository.
They shoukd be created in some temporary directories like .o, .so ...

2022-03-10 18:13 UTC, closed without merging

2022-03-10 18:15 UTC, perevbnlgov commented
pull request Star6_01 closed without merging. Wrong request.