Add FST hits in MuDst
star-bnl/star-sw pull request #341
Opened 2022-04-27 11:23 UTC by techuan-huang

The purpose of this PR is to set up FST hits in MuDst events. 

There are 3 additional classes (6 files) for FST was added (StMuFstCollection, StMuFstHit, and StMuFstUtil).
7 files are modified for adding the FST hits (StMuArrays, StMuDst, StMuDstMaker, and StMuTypes).

2022-05-03 15:37 UTC, starsdong commented
Hi experts, could you please take a look at this PR? Comment or approve this PR? To me I see the changes look straightforward and reasonable.

2022-05-03 15:57 UTC, sunxuhit approved these changes
Looks good to me.

2022-05-12 16:09 UTC, starsdong commented
Daniel, could you please take a look at this request, comment or approve this so we can include this into the library? Thanks

2022-05-16 12:23 UTC, jdbrice requested changes
Please bump the version of StMuDst
ClassDef(StMuDst,5) --> ClassDef(StMuDst,6)

2022-05-16 12:35 UTC, techuan-huang commented
Hi Daniel,
Thanks for the comment. I guess I also need to do this for StMuDstMaker?
ClassDef(StMuDstMaker, 8) --> ClassDef(StMuDstMaker, 9)?

2022-05-16 16:09 UTC, jdbrice approved these changes
Thanks for the updates

2022-05-16 16:09 UTC, merged