Update StMuEpdHit to include the DEP information
star-bnl/star-sw pull request #502
Opened 2023-03-17 14:54 UTC by plexoos

2023-03-20 17:50 UTC, klendathu2k approved these changes
Looks good to me.

2023-03-20 17:54 UTC, klendathu2k requested changes

2023-03-20 17:54 UTC, klendathu2k commented on StRoot/StMuDSTMaker/COMMON/StMuEpdHit.h
> +  Float_t mnMIP_QT;
... yes, missed this in my review.  Should keep the name the same.

2023-03-24 21:20 UTC, plexoos commented
Consolidated in #501

2023-03-24 21:20 UTC, closed without merging