Added mstu72 and mstu73 variable in StarGenPPEvent.*
star-bnl/star-sw pull request #559
Opened 2023-06-22 17:07 UTC by mrosales2016

Provided updates to StarGenPPEvent to include the mstu72 and mstu73 variables that will help delimit the event record based on Underlying Event and Parton Level. The two variables are defined using the Pythia common block PYDAT1 under the StarPythia6 framework.

2023-06-22 17:12 UTC, klendathu2k requested changes
When you change the memory layout of a persistent class in ROOT (i.e. anything that you wish to store in a ROOT file), you should increment the version number in the ClassDef file...

line 50 in StarGenPPEvent.h:
`ClassDef(StarGenPPEvent,1);   -->    ClassDef(StarGenPPEvent,2);`

2023-06-22 17:58 UTC, klendathu2k approved these changes

2023-06-23 16:43 UTC, plexoos approved these changes

2023-06-23 17:35 UTC, plexoos commented
Do these changes need to be pack ported to any of the past releases?

2023-06-23 17:41 UTC, klendathu2k commented
> Do these changes need to be backported to any of the past releases?

No.  We can wait for the next library release for this.

2023-06-23 17:49 UTC, merged