Fix daq5k gains, add TPC23 to chain
star-bnl/star-sw pull request #627
Opened 2023-11-06 00:05 UTC by fisyak

Fix daq5k TPC gains, Add TPC23 to the BFC chain.
See https://drupal.star.bnl.gov/STAR/blog/fisyak/TPC-daq5k-offline-cluster-finder-updates

2023-11-06 14:53 UTC, genevb reviewed
I would like some clarification on this....

At first glance, it looks like the new "TPC23" chain option is identical to the "TpxClu2D" chain option. However, the latter causes the "TpxClu2D" attribute to be set, while the former causes no attributes to be set, so they are slightly different. It does appear that the TPC hit maker codes do test for a "TPC23" attribute, but it's unclear where that gets set.

Is this the desired behavior, or should there be a line in StBFChain.cxx setting the "TPC23" attribute when this chain option is used?

2023-11-06 20:54 UTC, iraklic approved these changes

2023-11-06 21:04 UTC, klendathu2k requested changes
Generally looks fine.  I flagged two places where I would recommend improvements -- using standard StMaker mechanisms for saving histograms and making them available, plus standard access to makers -- but don't consider them show stoppers.  Once Gene's comments are addressed, I'll approve.

2023-11-06 21:04 UTC, klendathu2k commented on StRoot/StTpcHitMaker/StTpcHitMaker.h
> +  TH2C   *Thr() {return fThr;}
[minor].  Can diagnostic histograms be provided through the maker's histogram list mechanism, rather than direct access on the maker?

2023-11-06 21:04 UTC, klendathu2k commented on StRoot/StTpcHitMaker/StTpcRTSHitMaker.h
> +  static  StTpcRTSHitMaker *fgStTpcRTSHitMaker;
Again minor.  Would prefer to use the standard StMaker::GetMaker rather than static access method.

2023-11-15 17:29 UTC, genevb commented
> should there be a line in StBFChain.cxx setting the "TPC23" attribute when this chain option is used?

Just a comment that I think Yuri addressed this question.

2023-11-15 17:30 UTC, plexoos commented
Should we include this in SL23e?

2023-11-30 14:38 UTC, plexoos commented
If no further comments, let's merge

2023-12-01 19:39 UTC, merged